import CustomNavbar from './components/CustomNavbar'
import Footer from './components/Footer'
import UserProvider from './context/userProvider'
import './globals.css'
import { Inter } from 'next/font/google'
import { ToastContainer } from 'react-toastify'
import "react-toastify/dist/ReactToastify.css"
 

const inter = Inter({ subsets: ['latin'] })

//we've commented here because each link has its own metadata 
/*export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}*/

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-blue-200">
        <UserProvider children={children}>
          <ToastContainer/>
          <CustomNavbar />
            <div >{children}</div>
          <Footer/>
        </UserProvider>
      </body>
    </html>
  )
}
